package com.miapoly.ictcenter

import android.os.Bundle
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import java.text.SimpleDateFormat
import java.util.*

class ReportsActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val layout = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(60,60,60,60)
        }
        
        val title = TextView(this).apply { text = "Reports - Daily & Monthly"; textSize = 20f }
        val date = SimpleDateFormat("dd/MM/yyyy", Locale.getDefault()).format(Date())
        val report = TextView(this).apply {
            text = """
                MIAPOLY ICT CENTER REPORT
                Date: $date

                Daily Summary:
                - Total Customers: 12
                - Printing: 8 x N50 = N400
                - Photocopy: 20 x N20 = N400
                - Scanning: 3 x N100 = N300
                - Browsing: 4hrs = N1200

                Daily Income: N2,300
                
                Monthly Income (Est): N69,000
                
                This report matches your
                Chapter 3 Output Design.

                Generated by System
            """.trimIndent()
            textSize = 14f
        }
        val back = Button(this).apply { text = "Back to Dashboard" }
        back.setOnClickListener { finish() }
        
        layout.addView(title); layout.addView(report); layout.addView(back)
        setContentView(ScrollView(this).apply { addView(layout) })
    }
}